@baseUrl = http://localhost:8080
@authToken = {{authenticate.response.body.access_token}}


#@name create USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Romulo",
  "document": "10176372451",
  "email": "test@mail1.com.r2",
  "password": "Romulo$$14",
  "phone": "83981314690",
  "address": "rua mauri lira, numero 48",
  "role": "ROLE_ADMIN"
}


###############
# @name authenticate
POST {{baseUrl}}/users/auth
Content-Type: application/json

{
  "email": "test@mail1.com.r2",
  "password": "Romulo$$14"
}


####
GET {{baseUrl}}/users/profile
Authorization: Bearer {{authToken}}
Content-Type: application/json


####
# @name list users
# @description /users?query=00100200345&page=0&size=10
GET {{baseUrl}}/users?query=test@mail.com&page=0&size=10
Authorization: Bearer {{authToken}}
Content-Type: application/json