spring:
  application:
    name: car-rental-management

  datasource:
    url: jdbc:mysql://localhost:3306/cartrental?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:data/roles.sql
      
security:
  token:
    secret: ${JWT_SECRET:secret} 